<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.heartless' => '4ee45910d77acd942c19fd2b9524e6bee8ff39ea',
  'menu.main_menu' => '453b933d31a6f1d32ea94a8a85296d1391d30084',
  'views_view.heartless' => '14f24bf8688971c1ec2a17f02db0264c4e157c31',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'views',
);
